// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {youtube} from '../models';
import {main} from '../models';

export function GetVideoFromPlaylist(arg1:string):Promise<Array<youtube.PlaylistEntry>>;

export function SelectFolder():Promise<main.Folder>;

export function StartDownload(arg1:Array<string>,arg2:string):Promise<void>;

export function StopDownload():Promise<void>;
