// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVideoFromPlaylist(arg1) {
  return window['go']['main']['App']['GetVideoFromPlaylist'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartDownload(arg1, arg2) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2);
}

export function StopDownload() {
  return window['go']['main']['App']['StopDownload']();
}
